"""训练与评测产物命名约定。"""

from __future__ import annotations

RAW_DIRNAME = "raw"
STAGE_DIRNAME = "stage"
FINAL_DIRNAME = "final"

INITIAL_MODEL_DIRNAME = "initial_model"
LORA_DIRNAME = "lora"
CHECKPOINTS_DIRNAME = "checkpoints"
MERGED_MODEL_DIRNAME = "merged"
EVAL_DIRNAME = "eval"

METADATA_FILENAME = "metadata.json"

TRAIN_METRICS_ARTIFACT_NAME = "train_metrics"
VALIDATION_LABEL_METRICS_ARTIFACT_NAME = "validation_label_metrics"
TEST_METRICS_ARTIFACT_NAME = "test_metrics"
TEST_LABEL_METRICS_ARTIFACT_NAME = "test_label_metrics"
TEST_PREDICTIONS_ARTIFACT_NAME = "test_predictions"

TRAIN_METRICS_FILENAME = f"{TRAIN_METRICS_ARTIFACT_NAME}.csv"
VALIDATION_LABEL_METRICS_FILENAME = f"{VALIDATION_LABEL_METRICS_ARTIFACT_NAME}.csv"
TEST_METRICS_FILENAME = f"{TEST_METRICS_ARTIFACT_NAME}.csv"
TEST_LABEL_METRICS_FILENAME = f"{TEST_LABEL_METRICS_ARTIFACT_NAME}.csv"
TEST_PREDICTIONS_FILENAME = f"{TEST_PREDICTIONS_ARTIFACT_NAME}.csv"
EVAL_REPORT_FILENAME = "eval_report.xlsx"
TRAIN_LOSS_PLOT_FILENAME = "train_loss_plot.png"
TRAIN_EVAL_METRICS_PLOT_FILENAME = "train_eval_metrics_plot.png"


def build_eval_report_filename(run_id: str) -> str:
    """构建带 run_id 前缀的评测汇总 Excel 文件名。"""
    return f"{run_id}_{EVAL_REPORT_FILENAME}"

DEFAULT_EVAL_REPORT_ARTIFACT_NAMES: tuple[str, ...] = (
    TRAIN_METRICS_ARTIFACT_NAME,
    VALIDATION_LABEL_METRICS_ARTIFACT_NAME,
    TEST_METRICS_ARTIFACT_NAME,
    TEST_LABEL_METRICS_ARTIFACT_NAME,
    TEST_PREDICTIONS_ARTIFACT_NAME,
)

CSV_EVAL_ARTIFACT_NAMES: tuple[str, ...] = DEFAULT_EVAL_REPORT_ARTIFACT_NAMES